version: '3.8'
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto_broker
    ports:
      - "1883:1883" # Standard MQTT port
      - "9001:9001" # MQTT over WebSockets
    volumes:
      - ./mosquitto/config:/mosquitto/config # Mount custom config
      - ./mosquitto/data:/mosquitto/data # Persistent data
      - ./mosquitto/log:/mosquitto/log # Logs
    restart: unless-stopped
